version: "3.9"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 8888:8888
    networks:
      - backend

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    image: php:8.2-fpm
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - 8080:80

  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=lab11
    image: mysql:latest
    ports:
      - 3307:3306
    networks:
      - backend

  phpmyadmin:
    build:
      context: .
      dockerfile: Dockerfile.phpmyadmin
    ports:
      - 6001:80
    networks:
      - backend

networks:
  backend:
