name: Build and Publish

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REGISTRY: ghcr.io/wfgen

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and Push Docker images
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker-compose.yml
          platforms: ${{ matrix.architecture }}
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/nginx:${{ matrix.architecture }}
            ${{ env.DOCKER_REGISTRY }}/php:${{ matrix.architecture }}
            ${{ env.DOCKER_REGISTRY }}/mysql:${{ matrix.architecture }}
            ${{ env.DOCKER_REGISTRY }}/phpmyadmin:${{ matrix.architecture }}
